### ISSUE TITLE
Unable to load shared library 'glfw' or one of its dependencies

### ISSUE THREAD

**Issue by eouw0o83hf** [ForeverZer0/glfw-net#29]
First off, this library looks really fantastic. I was really excited to find it. Thanks for making it!

I'm seeing the following exception when trying to run one of the example projects:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'GLFW.Glfw' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'glfw' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libglfw, 1): image not found
   at GLFW.Glfw.Init()
   at GLFW.Glfw..cctor() in /Users/nathanlandis/Code/mivi/src/glfw-net/GLFW.NET/Glfw.cs:line 34
   --- End of inner exception stack trace ---
   at GLFW.Glfw.WindowHint(Hint hint, ClientApi value) in /Users/nathanlandis/Code/mivi/src/glfw-net/GLFW.NET/Glfw.cs:line 1776
   at HelloTriangle.Program.PrepareContext() in /Users/nathanlandis/Code/mivi/src/glfw-net/Examples/HelloTriangle/Program.cs:line 65
   at HelloTriangle.Program.Main(String[] args) in /Users/nathanlandis/Code/mivi/src/glfw-net/Examples/HelloTriangle/Program.cs:line 22
```

I'm running macOS 10.15.4 and have latest dotnet core sdks. I installed `glfw` using homebrew, and I've verified that it shows up in `/usr/local/include` and `lib`. I've tried a system reboot too.

Any idea of what I need to get the library to load correctly?

Thanks!

**Comment by eouw0o83hf** [comment]
h3. Update

I was able to resolve that issue by setting `LIBRARY` to:

```
public const string LIBRARY = "/usr/local/lib/libglfw.3.3.dylib";
```

However, now it's throwing another exception:

```
Unhandled exception. GLFW.Exception: NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above
   at GLFW.Glfw.GlfwError(ErrorCode code, IntPtr message) in /Users/nathanlandis/Code/mivi/src/glfw-net/GLFW.NET/Glfw.cs:line 1857
   at GLFW.Glfw.CreateWindow(Int32 width, Int32 height, Byte[] title, Monitor monitor, Window share)
   at GLFW.Glfw.CreateWindow(Int32 width, Int32 height, String title, Monitor monitor, Window share) in /Users/nathanlandis/Code/mivi/src/glfw-net/GLFW.NET/Glfw.cs:line 1485
   at HelloTriangle.Program.CreateWindow(Int32 width, Int32 height) in /Users/nathanlandis/Code/mivi/src/glfw-net/Examples/HelloTriangle/Program.cs:line 82
   at HelloTriangle.Program.Main(String[] args) in /Users/nathanlandis/Code/mivi/src/glfw-net/Examples/HelloTriangle/Program.cs:line 24
```

Any ideas?

**Comment by eouw0o83hf** [comment]
Managed to figure it out! For anyone else who finds this, take a look at the `Glfw.WindowHint()` registrations in `BasicExample/Program.cs`. You need to add one for `Glfw.WindowHint(Hint.OpenglForwardCompatible, true);`.
