### ISSUE TITLE
AcessViolation in FileDrop event

### ISSUE THREAD

**Issue by Ruannilton** [ForeverZer0/glfw-net#32]
```
 private static void OnWindowFileDrop(object sender, FileDropEventArgs e)
    {
        foreach (var item in e.Filenames)
        {
            Console.WriteLine(item);
        }
    }
```

Exception:
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr, Int32)
   at GLFW.Util.PtrToStringUTF8(IntPtr)
   at GLFW.NativeWindow.OnFileDrop(Int32, IntPtr)
   at GLFW.NativeWindow.<BindCallbacks>b__115_4(IntPtr, Int32, IntPtr)
   at GLFW.Glfw.WaitEvents()
   at GLFW.Glfw.WaitEvents()
   at Program.Main(System.String[])

**Comment by george-tsiros** [comment]
If you haven't fixed it already:
1) how are you setting the callback? are you doing something like

`GLFW.Glfw.SetDropCallback(Window, DropHandler) {
    //etc
}`

where `DropHandler` is the name of the method that does the handling?

If so, try defining a field of type `GLFW.FileDropCallback` and writing the "value" `DropHandler` to it after creating the window
